name: Backend Continuous Integration

# Workflow Control

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

# Workflow Jobs

jobs:
  Lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Checkout Run Lint
      run: cd starter/backend && pipenv run lint

  Test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Test
      working-directory: starter/backend 
      run:  |
        pipenv install pytest
        pipenv run test

  # Build job which runs only if Lint and Test pass 

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      working-directory: starter/backend 
      env:
        IMAGE_NAME: backend
      run: |
        docker build -t ${{env.IMAGE_NAME}}:latest .