name: Backend Continuous Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Checkout Run Lint
      run: cd starter/backend && pipenv run lint

  Test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Test
      run: cd starter/backend && pipenv install pytest && pipenv run test

      
  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3



    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      id: build-and-push
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: udacity
          IMAGE_TAG: ${{ github.sha }}
      run: |
          cd starter/backend
          docker build -t $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:backend-$IMAGE_TAG
    
    - name: Update Kubeconfig
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/backend/k8s
      env:
        IMAGE_TAG: ${{ github.sha }}
        REPO_NAME: backend
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1
        kustomize edit set image backend=677218928690.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG
        kustomize build | kubectl apply -f -
