# Frontend workflow integration
name: Frontend CI

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull events to the main branch
  pull_request:
    branches:
      - main

  
# Jobs defined in the workflow
jobs:
  lint:
    name: Lint-Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
        
      - name: Install Dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        run: |
          npm run lint
          
  test:
    name: Test-job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Check Code
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      
       - name: Install dependencies
        run: |
          npm ci
  
       - name: Run test
        run: npm run test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./starter/frontend

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json

        
      - name: Docker Build
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
          docker run --name mp-frontend -p 3000:3000 -d mp-frontend]
