name: Frontend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-20.04
   
    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci

    - name: Checkout Run Lint
      working-directory: starter/frontend
      run: npm run lint

  Test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json
    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci
  
    - name: Test
      working-directory: starter/frontend
      run: npm run test
     

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Code
      uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Build Docker Image
      run: |
        cd starter/frontend
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
       
    - name: Run Docker image
      run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend  
        
      

